DEBUG = True


GAME_WIDTH = 1280
GAME_HEIGHT = 720
RESOURCE_COLLECTION_AREA_WIDTH = 300
RESOURCE_COLLECTION_AREA_HEIGHT = 200
RESOURCES_BAR_HEIGHT = 100
ACTION_HEIGHT = GAME_HEIGHT - RESOURCE_COLLECTION_AREA_HEIGHT - RESOURCES_BAR_HEIGHT
